apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  tracing:
    type: None
  addons:
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: false
    grafana:
      enabled: false
